// <auto-generated />
using System;
using EventLog.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EventLog.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250219102243_AddInitialDbContext")]
    partial class AddInitialDbContext
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.18");

            modelBuilder.Entity("EventLog.Models.Entities.ApplicationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TestBool")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TestDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("TestInt32")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TestString")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ApplicationEntities");
                });

            modelBuilder.Entity("EventLog.Models.Entities.ApplicationOtherEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TestDecimal")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ApplicationOtherEntities");
                });

            modelBuilder.Entity("EventLog.Models.Entities.EntityLogEntry<EventLog.Models.Enums.EventType, EventLog.Models.Enums.EntityType, EventLog.Models.Enums.PropertyType>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActionType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EntityId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EntityType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EventLogEntryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EventLogEntryId");

                    b.ToTable("EntityLog");
                });

            modelBuilder.Entity("EventLog.Models.Entities.EventLogEntry<EventLog.Models.Enums.EventType, EventLog.Models.Enums.EntityType, EventLog.Models.Enums.PropertyType>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Details")
                        .HasColumnType("TEXT");

                    b.Property<int>("EventType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FailureDetails")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("EventLog");
                });

            modelBuilder.Entity("EventLog.Models.Entities.PropertyLogEntries.BoolPropertyLogEntry<EventLog.Models.Enums.EventType, EventLog.Models.Enums.EntityType, EventLog.Models.Enums.PropertyType>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EntityLogEntryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PropertyType")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EntityLogEntryId");

                    b.ToTable("BoolPropertyLog");
                });

            modelBuilder.Entity("EventLog.Models.Entities.PropertyLogEntries.DecimalPropertyLogEntry<EventLog.Models.Enums.EventType, EventLog.Models.Enums.EntityType, EventLog.Models.Enums.PropertyType>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EntityLogEntryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PropertyType")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EntityLogEntryId");

                    b.ToTable("DecimalPropertyLog");
                });

            modelBuilder.Entity("EventLog.Models.Entities.PropertyLogEntries.EventStatusDescription", b =>
                {
                    b.Property<int>("EnumId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.HasKey("EnumId");

                    b.ToTable("EventStatusDescriptions", "eventlog");
                });

            modelBuilder.Entity("EventLog.Models.Entities.PropertyLogEntries.EventTypeDescription", b =>
                {
                    b.Property<int>("EnumId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.HasKey("EnumId");

                    b.ToTable("EventTypeDescriptions", "eventlog");
                });

            modelBuilder.Entity("EventLog.Models.Entities.PropertyLogEntries.Int32PropertyLogEntry<EventLog.Models.Enums.EventType, EventLog.Models.Enums.EntityType, EventLog.Models.Enums.PropertyType>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EntityLogEntryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PropertyType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EntityLogEntryId");

                    b.ToTable("Int32PropertyLog");
                });

            modelBuilder.Entity("EventLog.Models.Entities.PropertyLogEntries.StringPropertyLogEntry<EventLog.Models.Enums.EventType, EventLog.Models.Enums.EntityType, EventLog.Models.Enums.PropertyType>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EntityLogEntryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PropertyType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EntityLogEntryId");

                    b.ToTable("StringPropertyLog");
                });

            modelBuilder.Entity("EventLog.Models.Entities.EntityLogEntry<EventLog.Models.Enums.EventType, EventLog.Models.Enums.EntityType, EventLog.Models.Enums.PropertyType>", b =>
                {
                    b.HasOne("EventLog.Models.Entities.EventLogEntry<EventLog.Models.Enums.EventType, EventLog.Models.Enums.EntityType, EventLog.Models.Enums.PropertyType>", "EventLogEntry")
                        .WithMany("EntityLogEntries")
                        .HasForeignKey("EventLogEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventLogEntry");
                });

            modelBuilder.Entity("EventLog.Models.Entities.PropertyLogEntries.BoolPropertyLogEntry<EventLog.Models.Enums.EventType, EventLog.Models.Enums.EntityType, EventLog.Models.Enums.PropertyType>", b =>
                {
                    b.HasOne("EventLog.Models.Entities.EntityLogEntry<EventLog.Models.Enums.EventType, EventLog.Models.Enums.EntityType, EventLog.Models.Enums.PropertyType>", "EntityLogEntry")
                        .WithMany("BoolPropertyLogEntries")
                        .HasForeignKey("EntityLogEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EntityLogEntry");
                });

            modelBuilder.Entity("EventLog.Models.Entities.PropertyLogEntries.DecimalPropertyLogEntry<EventLog.Models.Enums.EventType, EventLog.Models.Enums.EntityType, EventLog.Models.Enums.PropertyType>", b =>
                {
                    b.HasOne("EventLog.Models.Entities.EntityLogEntry<EventLog.Models.Enums.EventType, EventLog.Models.Enums.EntityType, EventLog.Models.Enums.PropertyType>", "EntityLogEntry")
                        .WithMany("DecimalPropertyLogEntries")
                        .HasForeignKey("EntityLogEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EntityLogEntry");
                });

            modelBuilder.Entity("EventLog.Models.Entities.PropertyLogEntries.Int32PropertyLogEntry<EventLog.Models.Enums.EventType, EventLog.Models.Enums.EntityType, EventLog.Models.Enums.PropertyType>", b =>
                {
                    b.HasOne("EventLog.Models.Entities.EntityLogEntry<EventLog.Models.Enums.EventType, EventLog.Models.Enums.EntityType, EventLog.Models.Enums.PropertyType>", "EntityLogEntry")
                        .WithMany("Int32PropertyLogEntries")
                        .HasForeignKey("EntityLogEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EntityLogEntry");
                });

            modelBuilder.Entity("EventLog.Models.Entities.PropertyLogEntries.StringPropertyLogEntry<EventLog.Models.Enums.EventType, EventLog.Models.Enums.EntityType, EventLog.Models.Enums.PropertyType>", b =>
                {
                    b.HasOne("EventLog.Models.Entities.EntityLogEntry<EventLog.Models.Enums.EventType, EventLog.Models.Enums.EntityType, EventLog.Models.Enums.PropertyType>", "EntityLogEntry")
                        .WithMany("StringPropertyLogEntries")
                        .HasForeignKey("EntityLogEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EntityLogEntry");
                });

            modelBuilder.Entity("EventLog.Models.Entities.EntityLogEntry<EventLog.Models.Enums.EventType, EventLog.Models.Enums.EntityType, EventLog.Models.Enums.PropertyType>", b =>
                {
                    b.Navigation("BoolPropertyLogEntries");

                    b.Navigation("DecimalPropertyLogEntries");

                    b.Navigation("Int32PropertyLogEntries");

                    b.Navigation("StringPropertyLogEntries");
                });

            modelBuilder.Entity("EventLog.Models.Entities.EventLogEntry<EventLog.Models.Enums.EventType, EventLog.Models.Enums.EntityType, EventLog.Models.Enums.PropertyType>", b =>
                {
                    b.Navigation("EntityLogEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
